version: 2.1

orbs:
  docker-image-extend: bigbite/docker-image-extend@0.0.2

parameters:
  docker_image_build:
    type: boolean
    default: false
  docker_image_repo:
    type: string
    default: 'false'
  docker_image_tag:
    type: string
    default: 'false'
  docker_image_args:
    type: string
    default: 'false'

jobs:
  build-docker-image:
    steps:
      - run:
          name: Create multiarch build
          command: docker buildx build --push --platform linux/amd64,linux/arm64 --tag << pipeline.parameters.docker_image_repo >>:<< pipeline.parameters.docker_image_tag >> .

workflows:
  workflow:
    jobs:
      - docker-image-extend/prepare:
          docker_repo: 'bigbite/jetty-wordpress-image'
          docker_image_build: '<< pipeline.parameters.docker_image_build >>'
          context: bigbite
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build-docker-image:
          docker_repo: 'bigbite/jetty-wordpress-image'
          docker_image_build: '<< pipeline.parameters.docker_image_build >>'
          context: bigbite
          filters:
            tags:
              ignore: /.*/
